// Generated by gencpp from file exercise2/ServiceRequest.msg
// DO NOT EDIT!


#ifndef EXERCISE2_MESSAGE_SERVICEREQUEST_H
#define EXERCISE2_MESSAGE_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise2
{
template <class ContainerAllocator>
struct ServiceRequest_
{
  typedef ServiceRequest_<ContainerAllocator> Type;

  ServiceRequest_()
    : station_ID(0)  {
    }
  ServiceRequest_(const ContainerAllocator& _alloc)
    : station_ID(0)  {
  (void)_alloc;
    }



   typedef int16_t _station_ID_type;
  _station_ID_type station_ID;





  typedef boost::shared_ptr< ::exercise2::ServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise2::ServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceRequest_

typedef ::exercise2::ServiceRequest_<std::allocator<void> > ServiceRequest;

typedef boost::shared_ptr< ::exercise2::ServiceRequest > ServiceRequestPtr;
typedef boost::shared_ptr< ::exercise2::ServiceRequest const> ServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise2::ServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise2::ServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise2::ServiceRequest_<ContainerAllocator1> & lhs, const ::exercise2::ServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.station_ID == rhs.station_ID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise2::ServiceRequest_<ContainerAllocator1> & lhs, const ::exercise2::ServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercise2::ServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise2::ServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::ServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::ServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::ServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::ServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise2::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aedbf9b210b5af3c248bf527a8382076";
  }

  static const char* value(const ::exercise2::ServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaedbf9b210b5af3cULL;
  static const uint64_t static_value2 = 0x248bf527a8382076ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise2::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise2/ServiceRequest";
  }

  static const char* value(const ::exercise2::ServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise2::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request\n"
"# std_msgs/Header header\n"
"int16 station_ID\n"
;
  }

  static const char* value(const ::exercise2::ServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise2::ServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.station_ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise2::ServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise2::ServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "station_ID: ";
    Printer<int16_t>::stream(s, indent + "  ", v.station_ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE2_MESSAGE_SERVICEREQUEST_H
