// Generated by gencpp from file exercise2/ServiceResponse.msg
// DO NOT EDIT!


#ifndef EXERCISE2_MESSAGE_SERVICERESPONSE_H
#define EXERCISE2_MESSAGE_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <exercise2/Message.h>

namespace exercise2
{
template <class ContainerAllocator>
struct ServiceResponse_
{
  typedef ServiceResponse_<ContainerAllocator> Type;

  ServiceResponse_()
    : header()
    , message()  {
    }
  ServiceResponse_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::exercise2::Message_<ContainerAllocator>  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::exercise2::ServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise2::ServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceResponse_

typedef ::exercise2::ServiceResponse_<std::allocator<void> > ServiceResponse;

typedef boost::shared_ptr< ::exercise2::ServiceResponse > ServiceResponsePtr;
typedef boost::shared_ptr< ::exercise2::ServiceResponse const> ServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise2::ServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise2::ServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise2::ServiceResponse_<ContainerAllocator1> & lhs, const ::exercise2::ServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise2::ServiceResponse_<ContainerAllocator1> & lhs, const ::exercise2::ServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercise2::ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise2::ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::ServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::ServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise2::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10cacc6f68c7bbd99eb534415926e511";
  }

  static const char* value(const ::exercise2::ServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10cacc6f68c7bbd9ULL;
  static const uint64_t static_value2 = 0x9eb534415926e511ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise2::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise2/ServiceResponse";
  }

  static const char* value(const ::exercise2::ServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise2::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response\n"
"std_msgs/Header header\n"
"Message message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: exercise2/Message\n"
"# name of the room\n"
"string room_name\n"
"\n"
"# ID of the room\n"
"int8 room_ID\n"
"\n"
"# level of charge of the robot battery\n"
"int8 charge_level\n"
;
  }

  static const char* value(const ::exercise2::ServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise2::ServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise2::ServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise2::ServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "message: ";
    s << std::endl;
    Printer< ::exercise2::Message_<ContainerAllocator> >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE2_MESSAGE_SERVICERESPONSE_H
